apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: cluster-autoscaler
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: MachineAPI
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  relatedObjects:
  - group: ""
    name: openshift-machine-api
    resource: namespaces
  - group: autoscaling.openshift.io
    name: ""
    resource: clusterautoscalers
  - group: autoscaling.openshift.io
    name: ""
    resource: machineautoscalers
